export const theListOfClasses = [
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript - מבוא",
        date: "3.7.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/-YPTjwck_0Q",
        theContentOfTheLesson: "מהו fullstack",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript - מבוא",
        date: "5.7.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://youtu.be/d57stbj2-GI",
        theContentOfTheLesson: "Variables",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript - מבוא",
        date: "10.7.22",
        theLessonNumber: "3",
        linkToTheLesson: "https://youtu.be/2BNsfgvRHCw",
        theContentOfTheLesson: "if",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript - מבוא",
        date: "12.7.22",
        theLessonNumber: "4",
        linkToTheLesson: "https://youtu.be/ibFLLv9IheY",
        theContentOfTheLesson: "if and while loops",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript - מבוא",
        date: "19.7.22",
        theLessonNumber: "5",
        linkToTheLesson: "https://classroom.google.com/c/NTM1Njk2NDgzNzU3/m/NTM3MTk5MzIwMzc4/details",
        theContentOfTheLesson: "for loops, Nested loop, and methods",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript - מבוא",
        date: "24.7.22",
        theLessonNumber: "6",
        linkToTheLesson: "https://youtu.be/_mFJxi2BA30",
        theContentOfTheLesson: "for in ",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript",
        date: "7.9.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/IhP9Fbv3Mjs",
        theContentOfTheLesson: "For loops (in & of),\n array methods",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "HTML",
        date: "7.9.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/yAAYl77Jqeg",
        theContentOfTheLesson: "HTML בסיס",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "javaScript",
        date: "11.9.22",
        theLessonNumber: '',
        linkToTheLesson: "https://www.youtube.com/watch?v=Dfqkex0e-J0",
        theContentOfTheLesson: " (array methods) תרגול וחזרה שיעורי בית",
        presentationsAndMore: "",
    },
    {
        teacherName: "חננאל פרל",
        theProgrammingLanguage: "SQL",
        date: "11.9.22",
        theLessonNumber: '1',
        linkToTheLesson: "https://www.youtube.com/watch?v=T7hfy696pI4",
        theContentOfTheLesson: "שאילתות בסיסיות",
        presentationsAndMore: "",
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript",
        date: "14.9.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://youtu.be/3i6OjIGGndg",
        theContentOfTheLesson: "פונקציות ורקורסיה",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "HTML",
        date: "14.9.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://www.youtube.com/watch?v=ajBz4xkUBWA",
        theContentOfTheLesson: "חזרה / class / id / getElementById",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "javaScript",
        date: "18.9.22",
        theLessonNumber: '',
        linkToTheLesson: "https://youtu.be/HuDdjccJ2wI",
        theContentOfTheLesson: " (גן חיות) תרגול וחזרה שיעורי בית",
        presentationsAndMore: "",
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "CSS",
        date: "14.9.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://www.youtube.com/watch?v=ajBz4xkUBWA",
        theContentOfTheLesson: "Base css and flex box",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript",
        date: "21.9.22",
        theLessonNumber: "3",
        linkToTheLesson: "https://www.youtube.com/watch?v=2ofyV9T1BJs",
        theContentOfTheLesson: "callBack and array methods (fiter)",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "CSS",
        date: "21.9.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://youtu.be/k8xGikRX4xw",
        theContentOfTheLesson: "Base css and flex box",
        presentationsAndMore: '',
    },
    {
        teacherName: "נריה",
        theProgrammingLanguage: "projects",
        date: "21.9.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/IERxRw0NtTo",
        theContentOfTheLesson: "Memory game 1",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "DOM",
        date: "2.10.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/7luH_l0QEpE",
        theContentOfTheLesson: "Get elements and events",
        presentationsAndMore: '',
    },
    {
        teacherName: "נריה",
        theProgrammingLanguage: "projects",
        date: "2.10.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://youtu.be/-XDm1KQoAL8",
        theContentOfTheLesson: "Memory game 2",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript",
        date: "19.10.22",
        theLessonNumber: "4",
        linkToTheLesson: "https://youtu.be/IdkQlMvmk5E",
        theContentOfTheLesson: "Array methods (find, map) \n Object ",
        presentationsAndMore: '',
    },
    {
        teacherName: "גולן",
        theProgrammingLanguage: "projects",
        date: "19.10.22",
        theLessonNumber: "3",
        linkToTheLesson: "https://youtu.be/0b6Xr9m-D9Y",
        theContentOfTheLesson: "Memory game 3",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "javaScript",
        date: "23.10.22",
        theLessonNumber: '',
        linkToTheLesson: "https://youtu.be/_SczSJjmyuo",
        theContentOfTheLesson: "(פרוייקט מסכם js) תרגול וחזרה שיעורי בית",
        presentationsAndMore: "",
    },
    {
        teacherName: "חננאל פרל",
        theProgrammingLanguage: "Git/github",
        date: "23.10.22",
        theLessonNumber: '1',
        linkToTheLesson: "https://youtu.be/v6lvCUVuq6g",
        theContentOfTheLesson: "Base git (init, add, log, status, commit, tag, diff and more)",
        presentationsAndMore: "",
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "javaScript",
        date: "26.10.22",
        theLessonNumber: "5",
        linkToTheLesson: "https://youtu.be/uVXApjEnTkg",
        theContentOfTheLesson: "פרוייקט מסכם js חזרה על  \nHTML \nאיסוף תוכן מאתרים",
        presentationsAndMore: '',
    },
    {
        teacherName: "גולן",
        theProgrammingLanguage: "projects",
        date: "26.10.22",
        theLessonNumber: "4",
        linkToTheLesson: "https://youtu.be/u02p-PHAB30",
        theContentOfTheLesson: "Tic Tac Toe",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "projects",
        date: "30.10.22",
        theLessonNumber: '5',
        linkToTheLesson: "https://youtu.be/_SczSJjmyuo",
        theContentOfTheLesson: "Create store in js",
        presentationsAndMore: "",
    },
    {
        teacherName: "חננאל פרל",
        theProgrammingLanguage: "Git/github",
        date: "30.10.22",
        theLessonNumber: '2',
        linkToTheLesson: "https://youtu.be/1u7ULxyleFc",
        theContentOfTheLesson: "branch, merge and more",
        presentationsAndMore: "",
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "JSON",
        date: "2.11.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/-_jHrBR3F0A",
        theContentOfTheLesson: "json and localStorage",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "React",
        date: "2.11.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/F7aD_JJT4Xk",
        theContentOfTheLesson: "הסבר על השפה",
        presentationsAndMore: '',
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "React",
        date: "2.11.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://youtu.be/ntweL0gZo10",
        theContentOfTheLesson: "Components and props",
        presentationsAndMore: '',
    },
    {
        teacherName: "נריה",
        theProgrammingLanguage: "projects",
        date: "26.10.22",
        theLessonNumber: "5",
        linkToTheLesson: "https://youtu.be/HScHk_cu_n4",
        theContentOfTheLesson: "Memory game portal",
        presentationsAndMore: '',
    },
    {
        teacherName: "יוסף שרביט",
        theProgrammingLanguage: "React",
        date: "6.11.22",
        theLessonNumber: '',
        linkToTheLesson: "https://youtu.be/byU0j8E8NIU",
        theContentOfTheLesson: "(Create store) תרגול וחזרה שיעורי בית",
        presentationsAndMore: "",
    },
    {
        teacherName: "חננאל פרל",
        theProgrammingLanguage: "Git/github",
        date: "6.11.22",
        theLessonNumber: '3',
        linkToTheLesson: "https://youtu.be/RvRGbdGJg24",
        theContentOfTheLesson: "Github",
        presentationsAndMore: "",
    },
    {
        teacherName: "אביעד דרלי",
        theProgrammingLanguage: "React",
        date: "9.11.22",
        theLessonNumber: '3',
        linkToTheLesson: "https://youtu.be/UtaEcHYLUWU",
        theContentOfTheLesson: "class constructor ,Mounting, Updating, Unmounting, useState",
        presentationsAndMore: "",
    },
    {
        teacherName: "נריה",
        theProgrammingLanguage: "projects",
        date: "9.11.22",
        theLessonNumber: "6",
        linkToTheLesson: "https://youtu.be/UtaEcHYLUWU",
        theContentOfTheLesson: "my playlist 1",
        presentationsAndMore: '',
    },
    {
        teacherName: "יעל",
        theProgrammingLanguage: "שיעורי עזר והשלמה",
        date: "13.11.22",
        theLessonNumber: "1",
        linkToTheLesson: "https://youtu.be/EqAcFyPDI4E",
        theContentOfTheLesson: "Clean code",
        presentationsAndMore: '',
    },
    {
        teacherName: "חננאל פרל",
        theProgrammingLanguage: "SQL",
        date: "13.11.22",
        theLessonNumber: "2",
        linkToTheLesson: "https://youtu.be/uNoSXlgblss",
        theContentOfTheLesson: "המשך ופונקציונליות בשפה",
        presentationsAndMore: '',
    },
]